version: 2
updates:

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      go-modules:
        patterns:
          - "*" # All go.mod dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"


  - package-ecosystem: docker
    directories:
      - /build/dev
      - /build/minimal
      - /build/full
      - /build/slim
    schedule:
      interval: daily
    groups:
      docker-updates:
        patterns:
          - "*"
