version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      disable:
        - printf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: 'QF1008:'
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
