repo_url: https://github.com/flanksource/canary-checker/
repo_name: Canary Checker
site_name: Canary Checker
theme:
  logo: ./images/cc-white.svg
  favicon: ./images/cc-blue.svg
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    # - navigation.expand
    - navigation.top
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - toc:
      permalink: False
      anchorlink: True
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite:
      linenums: true
nav:
  - Home: ./index.md
  - Quick Start:
    - Prerequisites: prereqs.md
    - Quick Start Guide: ./quick-start.md
  - Developer Guide: 
    - How to Install: ./installation.md
    - Running Locally: ./dev-guide.md
    - CLI: user-guide/run.md
    - Standalone Server: user-guide/server.md
    - Kubernetes Operator: user-guide/operator.md
    - Canary Types:
        - Cloudwatch: ./api/#cloudwatch
        - Containerd Pull: ./api/#containerdpull
        - Containerd Push: ./api/#containerdpush
        - DNS: ./api/#dns
        - Docker Pull: ./api/#dockerpull
        - Docker Push: ./api/#dockerpush
        - EC2: ./api/#ec2
        - GCS: ./api/#gcsbucket
        - Helm: ./api/#helm
        - HTTP: ./api/#http
        - ICMP: ./api/#icmp
        - JMeter: ./api/#jmeter
        - JUnit: ./api/#junit
        - LDAP: ./api/#ldap
        - Mongo: ./api/#mongo
        - Namespace: ./api/#namespace
        - Pod: ./api/#pod
        - Postgres: ./api/#postgres
        - Prometheus: ./api/#prometheus
        - Redis: ./api/#redis
        - Restic: ./api/#restic
        - S3 Bucket: ./api/#s3bucket
        - S3: ./api/#s3
        - SMB / CIFS: ./api/#smb
        - SQL Server: ./api/#mssql


