# OSV-Scanner Configuration
# Used by OpenSSF Scorecard for vulnerability scanning
# Documentation: https://google.github.io/osv-scanner/configuration/

# Ignore specific vulnerabilities that are accepted risks
[[IgnoredVulns]]
id = "GO-2022-0635"
# In-band key negotiation issue in AWS S3 Crypto SDK
# Reason: Not called by our codebase (verified with govulncheck)
# Module: github.com/aws/aws-sdk-go (indirect dependency only)
# Review Date: 2025-10-29
reason = "Not exploitable - S3 crypto functions not used by our code. See SECURITY.md for details."

[[IgnoredVulns]]
id = "GO-2022-0646"
# CBC padding oracle issue in AWS S3 Crypto SDK
# Reason: Not called by our codebase (verified with govulncheck)
# Module: github.com/aws/aws-sdk-go (indirect dependency only)
# Review Date: 2025-10-29
reason = "Not exploitable - S3 crypto functions not used by our code. See SECURITY.md for details."
