apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "canary-checker.name" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "canary-checker.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "canary-checker.name" . }}-sa
    namespace: {{ .Release.Namespace }}
