apiVersion: rbac.authorization.k8s.io/v1
kind: "{{if .Values.serviceAccount.rbac.clusterRole}}Cluster{{end}}RoleBinding"
metadata:
  name: {{ include "canary-checker.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "{{if .Values.serviceAccount.rbac.clusterRole}}Cluster{{end}}Role"
  name: {{ include "canary-checker.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "canary-checker.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
