apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canary-checker.name" . }}
  labels:
    {{- include "canary-checker.labels" . | nindent 4 }}
data:
  canary-checker.properties: |
    {{- range $k, $v := .Values.disableChecks }}
    check.disabled.{{ $k }}={{ $v }}
    {{- end }}
