{{- if eq .Values.db.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "canary-checker.labels" . | nindent 4 }}
spec:
  selector:
    app: postgresql
    {{- include "canary-checker.selectorLabels" . | nindent 4 }}
  ports:
  - port: 5432
    targetPort: 5432
{{- end }}
