apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-initialisation
  labels:
    app: postgres-initialisation
    {{- include "canary-checker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      name: postgres-initialisation
      labels:
        app: postgres-initialisation
        {{- include "canary-checker.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: postgres-initialisation
          image: docker.io/postgres:14
          args: ["psql", "-U", "$(POSTGRES_USER)", "-h", "$(POSTGRES_HOST)", "-d", "postgres", "-c", "CREATE DATABASE canarychecker"]
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretKeyRef.name }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretKeyRef.name }}
                  key: POSTGRES_PASSWORD
