{{- if eq .Values.db.enabled true }}
{{- if .Values.db.secretKeyRef.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretKeyRef.name }}
  labels:
    {{- include "canary-checker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- $secretObj := ( lookup "v1" "Secret" .Release.Namespace "postgres-connection" ).data }}
  {{- $user := (( get $secretObj "POSTGRES_USER" ) | b64dec ) | default "postgres" }}
  {{- $password := (( get $secretObj "POSTGRES_PASSWORD" ) | b64dec ) | default ( randAlphaNum 32 ) }}
  {{- $host := print "postgres." .Release.Namespace  ".svc.cluster.local" }}
  {{- $url := print "postgresql://" $user ":" $password "@" $host }}
  {{- $canaryCheckerUrl := ( get $secretObj .Values.db.secretKeyRef.key ) | default ( print $url "/canarychecker" ) }}
  POSTGRES_USER: {{ $user | quote }}
  POSTGRES_PASSWORD: {{ $password | quote }}
  POSTGRES_HOST: {{ $host | quote }}
  POSTGRES_PORT: "5432"
  {{ .Values.db.secretKeyRef.key }}: {{ $canaryCheckerUrl | quote }}
{{- end }}
{{- end }}
