{{- if eq .Values.db.external.create true }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  selector:
    app: postgresql
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  ports:
  - port: 5432
    targetPort: 5432
{{- end }}
