apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "canary-checker.name" . }}-priority
value: -1
globalDefault: false
description: "This priority class should be used for canary pods only."
