{{- if .Values.serviceAccount.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: "{{if .Values.serviceAccount.rbac.clusterRole}}Cluster{{end}}Role"
metadata:
  name: {{ include "canary-checker.name" . }}-role
rules:
  {{- if .Values.serviceAccount.rbac.secrets}}
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  {{- end}}
  {{- if .Values.serviceAccount.rbac.configmaps}}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  {{- end}}
  {{- if .Values.serviceAccount.rbac.exec}}
  - apiGroups: [""]
    resources:
      - pods/attach
      - pods/exec
      - pods/log
    verbs:
      - '*'
  {{- end}}
  {{- if .Values.serviceAccount.rbac.tokenRequest}}
  - apiGroups:
      - authentication.k8s.io
    resources:
      - serviceaccounts/token
    verbs:
      - create
  {{- end}}
  {{- if .Values.serviceAccount.rbac.readAll}}
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
  {{- end}}
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries
      - topologies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries/status
      - topologies/status
    verbs:
      - get
      - patch
      - update
  {{- if .Values.serviceAccount.rbac.podsCreateAndDelete}}
  # for creating and destroying pods during the pod canary test
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
    verbs:
      - "*"
  {{- end}}
  {{- if .Values.serviceAccount.rbac.ingressCreateAndDelete }}
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - "*"
  {{- end}}
  {{- if .Values.serviceAccount.rbac.namespaceCreateAndDelete }}
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - "*"
  {{- end}}
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # for leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: "{{if .Values.serviceAccount.rbac.clusterRole}}Cluster{{end}}RoleBinding"
metadata:
  name: {{ include "canary-checker.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "{{if .Values.serviceAccount.rbac.clusterRole}}Cluster{{end}}Role"
  name: {{ include "canary-checker.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end}}