{{- if .Values.upstream.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canary-checker.name" . }}
data:
  UPSTREAM_USERNAME: {{ .Values.upstream.username | b64enc }}
  UPSTREAM_PASSWORD: {{ .Values.upstream.password | b64enc }}
{{- end }}
