// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CheckStatuses string
	Checks        string
	Component     string
	System        string
}{
	CheckStatuses: "check_statuses",
	Checks:        "checks",
	Component:     "component",
	System:        "system",
}
