apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: docker-pass
spec:
  interval: 30
  docker:
    - image: docker.io/library/busybox:1.31.1
      expectedDigest: 6915be4043561d64e0ab0f8f098dc2ac48e077fe23f488ac24b665166898115a
      expectedSize: 1219782
