apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canary-checker
resources:
  - ./base
  - ./namespace.yaml
  - ./deploy/Canary.yml
  - ./deploy/Topology.yml
  - ./deploy/Component.yml
images:
  - name: controller
    newName: docker.io/flanksource/canary-checker
    newTag: latest
