{
 "title": "Canary Checker Overview",
 "description": "High level overview of canary status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Canary",
    "query": {
     "query": "label_values(canary_check_info, canary_name)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(canary_check_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Canaries",
   "type": "marcusolsson-hexmap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(canary_name) (canary_check{namespace=\"$Namespace\"})",
     "legendFormat": "{{canary_name}}"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "marcusolsson-hexmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "repeat": "namespace",
   "targets": [
    {
     "expr": "sum by(canary_name,name,key) (canary_check_info{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Canary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "repeat": "Canary",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(canary_check{canary_name=\"$Canary\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}