/*
 * Canary Checker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1..1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Summary struct {
	Healthy int32 `json:"healthy,omitempty"`
	Info int32 `json:"info,omitempty"`
	Unhealthy int32 `json:"unhealthy,omitempty"`
	Warning int32 `json:"warning,omitempty"`
}
