/*
 * Canary Checker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1..1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Latency struct {
	P95 float64 `json:"p95,omitempty"`
	P97 float64 `json:"p97,omitempty"`
	P99 float64 `json:"p99,omitempty"`
	Rolling1h float64 `json:"rolling1h,omitempty"`
}
