/*
 * Canary Checker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1..1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Config struct {
	ConfigType string `json:"config_type,omitempty"`
	ExternalId []string `json:"external_id,omitempty"`
	ExternalType string `json:"external_type,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Spec *interface{} `json:"spec,omitempty"`
}
