/*
 * Canary Checker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1..1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckStatus struct {
	Duration int32 `json:"duration,omitempty"`
	Error_ string `json:"error,omitempty"`
	Invalid bool `json:"invalid,omitempty"`
	Message string `json:"message,omitempty"`
	Status bool `json:"status,omitempty"`
	Time string `json:"time,omitempty"`
}
