/*
 * Canary Checker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1..1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Uptime struct {
	Failed int32 `json:"failed,omitempty"`
	P100 float64 `json:"p100,omitempty"`
	Passed int32 `json:"passed,omitempty"`
}
