on:
  pull_request:
permissions:
  contents: read
  checks: read
  issues: read
  pull-requests: read
name: Go Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26.x
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            cache-
      - name: Test
        run: make test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always() && github.event.repository.fork == 'false'
        with:
          files: test/test-results.xml
          check_name: E2E - ${{matrix.suite}}
