name: Helm Test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e # v2.0.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          driver-opts: network=kind
          buildkitd-flags: --allow-insecure-entitlement network.host
          buildkitd-config-inline: |
            [registry."kind-registry:5000"]
              http = true
              insecure = true

      - name: Build and push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ./build/full/Dockerfile
          push: true
          tags: kind-registry:5000/flanksource/canary-checker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          KIND_REGISTRY: kind-registry:5000

      - name: Update canary-checker image in helm chart
        uses: mikefarah/yq@0f4fb8d35ec1a939d78dd6862f494d19ec589f19 # v4.52.5
        with:
          cmd: yq -i e '.global.imageRegistry = "kind-registry:5000"' chart/values.yaml

      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.20.0

      - name: Package helm chart
        run: |
          helm dependency build ./chart
          helm package ./chart --version 1.0.0

      - name: Install helm chart
        run: "helm install canary-checker canary-checker-1.0.0.tgz -n canary-checker --create-namespace"

      - name: Wait for 30 seconds
        run: "kubectl rollout status deploy/canary-checker -n canary-checker --timeout 5m"

      - name: Check canary-checker pods
        run: "kubectl describe pods -n canary-checker"

      - name: Run tests
        run: ./chart/test.sh canary-checker

      - name: Check logs
        run: kubectl logs deploy/canary-checker -n canary-checker
        if: always()
