name: Create Release
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      version:
        description: New version to create
        required: false
        default: ""
      channel:
        description: "Release channel"
        required: true
        default: "rc"
        type: choice
        options:
          - stable
          - rc

permissions:
  contents: write
  packages: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ env.VERSION  || steps.semantic.outputs.new_release_version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set branch variable for semantic release
        run: |
          if [[ "${{ inputs.version }}" != "" ]]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
            echo "TAG=v${{ inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=" >> $GITHUB_ENV
          fi

          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            if [[  "${{ inputs.channel }}" ==  "stable" ]]; then
              BRANCHES="['master']"
            elif [[  "${{ inputs.channel }}" ==  "rc" ]]; then
              BRANCHES="[{name: 'master', channel: 'rc', prerelease: 'rc'}, {name: 'dummy-release'}]"
            fi
          else
            BRANCHES="[{name: 'master', channel: 'beta', prerelease: 'beta'}, {name: 'dummy-release'}]"
          fi
          echo "BRANCHES=$BRANCHES" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        if: ${{ ! env.TAG }}
        id: semantic
        with:
          branches: ${{ env.BRANCHES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        if: ${{ env.TAG }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.TAG }}',
              sha: context.sha
            })
  binary:
    runs-on: ubuntu-latest
    needs: semantic-release
    strategy:
      fail-fast: false
      matrix:
        os: [linux, darwin, windows]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: v1.26.x

      - run: make ${{matrix.os}} compress
        env:
          VERSION: v${{ needs.semantic-release.outputs.release-version }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./.release/*
          tag: v${{ needs.semantic-release.outputs.release-version }}
          overwrite: true
          file_glob: true

  docker:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clear up disk space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf $AGENT_TOOLSDIRECTORY
          rm -rf /opt/hostedtoolcache

      - name: Set version
        # Always use git tags as semantic release can fail due to rate limit
        run: |
          git fetch --prune --unshallow
          echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags | sed -e 's/^v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx #must be executed before a step that contains platforms
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@376925c9d111252e87ae59691e5a442dd100ef6a # v2.1.3
        with:
          registry-type: public

      - name: Publish Minimal Image to Dockerhub & ECR Public
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k4y9r6y5
          REPOSITORY: canary-checker
          IMAGE_TAG: "v${{ env.RELEASE_VERSION }}"
        with:
          context: .
          file: build/minimal/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker.io/flanksource/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker.io/flanksource/${{ env.REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-full:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clear up disk space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf $AGENT_TOOLSDIRECTORY
          rm -rf /opt/hostedtoolcache

      - name: Set version
        # Always use git tags as semantic release can fail due to rate limit
        run: |
          git fetch --prune --unshallow
          echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags | sed -e 's/^v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx #must be executed before a step that contains platforms
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@376925c9d111252e87ae59691e5a442dd100ef6a # v2.1.3
        with:
          registry-type: public

      - name: Publish image to Dockerhub & ECR Public
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k4y9r6y5
          REPOSITORY: canary-checker
          IMAGE_TAG: "v${{ env.RELEASE_VERSION }}"
        with:
          context: .
          file: build/full/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-full
            docker.io/flanksource/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-full
            docker.io/flanksource/${{ env.REPOSITORY }}:latest-full
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-slim:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clear up disk space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf $AGENT_TOOLSDIRECTORY
          rm -rf /opt/hostedtoolcache

      - name: Set version
        # Always use git tags as semantic release can fail due to rate limit
        run: |
          git fetch --prune --unshallow
          echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags | sed -e 's/^v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx #must be executed before a step that contains platforms
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@376925c9d111252e87ae59691e5a442dd100ef6a # v2.1.3
        with:
          registry-type: public

      - name: Publish Image to Dockerhub & ECR Public
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k4y9r6y5
          REPOSITORY: canary-checker
          IMAGE_TAG: "v${{ env.RELEASE_VERSION }}"
        with:
          context: .
          file: build/slim/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-slim
            docker.io/flanksource/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-slim
            docker.io/flanksource/${{ env.REPOSITORY }}:latest-slim
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm:
    runs-on: ubuntu-latest
    needs: [semantic-release, docker, docker-slim, docker-full]
    if: always()
    outputs:
      release-version: ${{ steps.version.outputs.release-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install yq
        uses: mikefarah/yq@0f4fb8d35ec1a939d78dd6862f494d19ec589f19 # v4.52.5
      - name: Set version
        id: version
        # Always use git tags as semantic release can fail due to rate limit
        run: |
          git fetch --prune --unshallow
          VERSION=$(git describe --abbrev=0 --tags | sed -e 's/^v//')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "release-version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update chart version
        run: yq -i e '.version = "${{ env.RELEASE_VERSION }}"' chart/Chart.yaml
      - name: Update app version
        run: yq -i e '.appVersion = "${{ env.RELEASE_VERSION }}"' chart/Chart.yaml
      - name: Update image tags
        run: yq -i e '.image.tag = "v${{ env.RELEASE_VERSION }}"' chart/values.yaml
      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.20.0
      - name: Package Helm chart
        run: |
          make chart
      - name: Upload helm chart artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: helm-chart
          path: canary-checker-*.tgz

  push-helm-chart:
    needs: helm
    if: always() && needs.helm.result == 'success'
    uses: flanksource/action-workflows/.github/workflows/push-helm-chart.yml@4b41aaf6cf7727789c0d21cd0bc262e850ba543f # main
    with:
      filename_regex: "canary-checker-*.tgz"
      version: ${{ needs.helm.outputs.release-version }}
      pr_title: "Release ${{ needs.helm.outputs.release-version }} of ${{ github.repository }}"
    secrets:
      token: ${{ secrets.FLANKBOT }}
